apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xhs-aio
  namespace: sandbox
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: sandbox-xhs-aio-strip@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - sandbox.cyber-psychosis.net
      secretName: sandbox-tls
  rules:
    - host: sandbox.cyber-psychosis.net
      http:
        paths:
          - path: /services/xhs-aio
            pathType: Prefix
            backend:
              service:
                name: xhs-aio
                port:
                  number: 8000
